name: app_database
description: "A new Flutter package project."
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.23.0
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.21.2
  build_runner:
  sizzle_lints:
