arb-dir: lib/src/core/localization/translations
template-arb-file: app_en.arb
output-localization-file: generated_localizations.dart
output-class: GeneratedLocalizations
output-dir: lib/src/core/localization/generated
nullable-getter: false
synthetic-package: false