name: blaze_starter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.4+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.1.0
  go_router: 5.0.1
  intl: 0.17.0
  json_annotation: 4.7.0
  l: 3.2.0
  purple_lints: 0.3.0
  shared_preferences: 2.0.15
  stack_trace: 1.10.0
  theme_tailor_annotation: 1.0.3
  

dev_dependencies:
  build_runner: 2.2.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  go_router_builder: 1.0.14
  json_serializable: 6.4.0
  theme_tailor: 1.0.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
