name: rest_client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.1
  http: ^1.2.2
  intercepted_client: ^0.0.1
  path:
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  sizzle_lints:
